version: '3'

services:
  plant-db:
    image: 'postgres:13.1-alpine'
    ports:
      - "45533:5432"
    container_name: plant-db
    environment:
      - POSTGRES_USER=openSchool1
      - POSTGRES_PASSWORD=openSchool1
      - POSTGRES_DB=openSchool1
  metric-db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5433:5432"
    container_name: metric-db
    environment:
      - POSTGRES_USER=metric
      - POSTGRES_PASSWORD=metric
      - POSTGRES_DB=metrics
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181